version: '3.8'

services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=tech_hub
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - laravel-network
    restart: always

  laravel:
    image: bitnami/laravel:latest
    container_name: laravel
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=tech_hub
    volumes:
      - ./:/app
    networks:
      - laravel-network
    depends_on:
      - mariadb
    restart: always
    command: /bin/sh -c "cp .env.example .env && php artisan key:generate && composer install && php artisan serve --host=0.0.0.0 --port=8000 & npm install && npm run dev"

volumes:
  mariadb_data:
    driver: local

networks:
  laravel-network:
    driver: bridge
